spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null