spring:
  data:
    mongodb:
      auto-index-creation: true
      host: ${MONGGO_HOST}
      port: ${MONGGO_PORT}
      database: ${MONGGO_DATABASE}
      authentication-database: admin
      username: ${MONGGO_USERNAME}
      password: ${MONGGO_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}