spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}